In [6]:
import pandas as pd
from os import path

In [18]:
print(os.getcwd())
os.chdir('/Users/spencerwillard/code/local/fraud_detection_project/')
print(os.getcwd())

/Users/spencerwillard/code/local/fraud_detection_project/data
/Users/spencerwillard/code/local/fraud_detection_project

In [ ]:
apps = pd.read_csv("data/raw/applications.csv")
outcomes = pd.read_csv("data/raw/outcomes.csv")

In [20]:
apps.head()

   application_id     application_date  identity_risk_score
0               1  2023-01-01 00:00:00                  102
1               2  2023-01-01 01:00:00                  435
2               3  2023-01-01 02:00:00                  860
3               4  2023-01-01 03:00:00                  270
4               5  2023-01-01 04:00:00                  106

In [21]:
outcomes.head()

   application_id  fraud account_status charged_off
0               1      0           open          no
1               2      0           open          no
2               3      1      prevented         yes
3               4      0           open          no
4               5      0           open          no

In [27]:
outcomes["fraud"].value_counts()

fraud
0    5936
1    4064
Name: count, dtype: int64

In [28]:
outcomes["fraud"].mean()

np.float64(0.4064)